server:
  port: 8888
debug: true
spring:
  profiles:
    active: dev

  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
  redis:
  # Redis数据库索引（默认为0）
    database: 3
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器地址
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
    # 连接池中的最大空闲连接
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最小空闲连接
      min-idle: 0
  # 连接超时时间（毫秒）
    timeout: 0

mybatis:
  type-aliases-package: com.example.mapper
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
mapper:
  not-empty: false
  identity: = MYSQL
  mappers: com.example.common.base.BaseDao


